### ISSUE TITLE
Create Specification of "Blog"

### ISSUE THREAD

**Issue by FindAirin** [Team-Kumquat/SoftUni-QA-Blog#1]
Create Specification of "Blog":
- available functionality
- available screens
- required development settings (IDE, SQL, etc.) to open and run the solution
- deployment settings (what machine and settings will be needed for deploying the application)
- should have functionality in comparison with other blogs *optional

**Comment by FindAirin** [comment]
I uploaded a general SRS template, so we can start with sections 1 and 2 related to the functionality and the purpose of the provided Blog application.

**Comment by zutobg** [comment]
I found out that you upload it to the wrong repo - the forked one into your account here https://github.com/FindAirin/SoftUni-QA-Blog/commit/0565734f0c6620ba018879391482686361f99e5a

> Check the TOC of the document. It includes brief descriptions what should be added in each point. Until we determine which points will be required, we can start filling 1 and 2 sections. I added clarifications in most points.
I guess point 3 will be related to the test plan we will create. We can remove points.

I download the SRS template and commit it into the original repo here https://github.com/Team-Kumquat/SoftUni-QA-Blog/commit/8b1de10b9fbc6e29503d81e8274733cc5d4f48b2

And since "tracking changes in a DOCX file in git is an awful thing" lets collaborate here https://docs.google.com/document/d/1NBflHhMNueFB3_Kr3Biua-dQ-xoFoumCZWdZ1aqIDEU/edit?usp=sharing

**Comment by FindAirin** [comment]
simple SRS is added
